# Generated by Django 3.2.9 on 2021-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_eligible',
            field=models.BooleanField(default=False, help_text='Designates whether the user can is eligible for credit purchase.', verbose_name='Credit status'),
        ),
    ]
